name: Build and Release Extension

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build extension
        run: |
          zip -r bilingual-ard.xpi manifest.json background.js content.js style.css doc/ LICENSE README.md

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: bilingual-ard.xpi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
